--TB_BOOK 테이블 생성


CREATE TABLE TB_BOOK (
BOOK_NO NUMBER CONSTRAINT TB_BOOK_PK PRIMARY KEY,
BOOK_TITLE VARCHAR2(50) NOT NULL,
WRITER VARCHAR2(30),
REVIEW_CONTENT VARCHAR(4000) NOT NULL,
REVIEW_WRITER VARCHAR2(10) NOT NULL,
RATE NUMBER NOT NULL CHECK (RATE BETWEEN 1 AND 10),
REG_DATE DATE DEFAULT SYSDATE
);

DROP TABLE TB_BOOK;

COMMENT ON COLUMN TB_BOOK.BOOK_NO IS '번호';
COMMENT ON COLUMN TB_BOOK.BOOK_TITLE IS '도서 이름';
COMMENT ON COLUMN TB_BOOK.WRITER IS '작가';
COMMENT ON COLUMN TB_BOOK.REVIEW_CONTENT IS '리뷰 내용';
COMMENT ON COLUMN TB_BOOK.REVIEW_WRITER IS '작성자';
COMMENT ON COLUMN TB_BOOK.RATE IS '평점';
COMMENT ON COLUMN TB_BOOK.REG_DATE IS '등록일';






SELECT * FROM TB_BOOK;

DROP TABLE TB_BOOK;

CREATE SEQUENCE SEQ_BOOK_NO NOCACHE;
DROP SEQUENCE SEQ_BOOK_NO;

INSERT INTO TB_BOOK
VALUES(SEQ_BOOK_NO.NEXTVAL,'테스트제목1','테스트작가1','테스트리뷰1','작성자1',5,DEFAULT);
INSERT INTO TB_BOOK
VALUES(SEQ_BOOK_NO.NEXTVAL,'테스트제목2','테스트작가2','테스트리뷰2','작성자2',5,DEFAULT);
INSERT INTO TB_BOOK
VALUES(SEQ_BOOK_NO.NEXTVAL,'테스트제목3','테스트작가3','테스트리뷰3','작성자3',5,DEFAULT);
INSERT INTO TB_BOOK
VALUES(SEQ_BOOK_NO.NEXTVAL,'테스트제목4','테스트작가4','테스트리뷰4','작성자4',5,DEFAULT);
INSERT INTO TB_BOOK
VALUES(SEQ_BOOK_NO.NEXTVAL,'테스트제목5','테스트작가5','테스트리뷰5','작성자5',5,DEFAULT);
COMMIT;
DELETE FROM TB_BOOK WHERE BOOK_TITLE = '테스트제목4';
DELETE FROM TB_BOOK WHERE BOOK_TITLE = '테스트제목5';

SELECT BOOK_NO, BOOK_TITLE, REVIEW_WRITER, RATE, TO_CHAR(REG_DATE,'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_BOOK ORDER BY BOOK_NO ASC;

SELECT BOOK_NO, BOOK_TITLE,WRITER,REVIEW_CONTENT ,REVIEW_WRITER,
TO_CHAR(REG_DATE,'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_BOOK
WHERE BOOK_NO = 1;
;



INSERT INTO TB_BOOK VALUES (SEQ_BOOK_NO.NEXTVAL,BOOK_TITLE,WRITER,REVIEW_CONTENT,REVIEW_WRITER,RATE,DEFAULT);

SELECT BOOK_NO, BOOK_TITLE, WRITER, REVIEW_WRITER, RATE, TO_CHAR(REG_DATE,'YYYY-MM-DD HH24:MI:SS') REG_DATE FROM TB_BOOK
WHERE BOOK_NO = 1;


SELECT BOOK_NO, BOOK_TITLE, WRITER, REVIEW_WRITER, RATE, TO_CHAR(REG_DATE,'YYYY-MM-DD HH24:MI:SS') REG_DATE
FROM TB_BOOK ORDER BY BOOK_NO;